[package]
name = "chompy"
version = "0.0.0"
edition = "2021"

[lib]
name = "chompy"
path = "src/lib.rs"

[dependencies]
codespan-reporting = "0.11"
pretty_assertions = "1.1"
hashbrown = { version = "0.13", features = ["serde"] }
static_assertions = "1.1"
peekmore = "1"
